[metrics]
weekly = ["fxview_opened", "have_colorways"]
overall = ["fxview_opened", "have_colorways"]

[metrics.fxview_opened]
data_source = "events"
select_expression = "CAST(SUM(CASE WHEN event_category = 'firefoxview' AND event_method = 'entered' THEN 1 ELSE 0 END) > 0 AS INT)"

[metrics.fxview_opened.statistics.binomial]


[metrics.have_colorways]
data_source = "main"
select_expression = "CAST(COALESCE(LOGICAL_OR(environment.addons.theme.id LIKE '%colorway%mozilla.org'), FALSE) AS INT)"

[metrics.have_colorways.statistics.binomial]

[data_sources]

[data_sources.events]
from_expression = """(
    SELECT *
    FROM `mozdata.telemetry.events` ds
    WHERE `mozfun.map.get_key`(
        ds.experiments, 'colorways-expiring-fx108'
    ).branch IS NOT NULL    
)"""
experiments_column_type = "native"
friendly_name = "Events"
description = "Events Ping"


[data_sources.main]
from_expression = """(
    SELECT
        *,
        DATE(submission_timestamp) AS submission_date,
        environment.experiments
    FROM `moz-fx-data-shared-prod`.telemetry_stable.main_v4 ds
    WHERE `mozfun.map.get_key`(
        ds.environment.experiments, 'colorways-expiring-fx108'
    ).branch IS NOT NULL
)"""
experiments_column_type = "native"
friendly_name = "Main"
description = "Main ping table"
