[experiment]

[data_sources.events_unnested]
from_expression = """(
  SELECT
    *
FROM
  `moz-fx-data-shared-prod.firefox_desktop.events` AS e
CROSS JOIN
  UNNEST(e.events) AS event
)"""

[metrics]

weekly = [
    "ad_clicks_on_serps_from_glean",
    "serps_with_ads_from_glean",
]

overall = [
    "ad_clicks_on_serps_from_glean",
    "serps_with_ads_from_glean",
]

[metrics.ad_clicks_on_serps_from_glean]
select_expression = '''
    COUNTIF(event.category = 'serp' AND event.name = 'engagement'
    AND ARRAY_LENGTH(ARRAY(
      SELECT
        1
      FROM
        UNNEST(event.extra) AS extra
      WHERE
        (extra.key = 'target'
          AND extra.value IN ( 'ad_link',
            'ad_sitelink',
            'ad_carousel',
            'ad_sidebar') ))) >= 1)
'''
data_source = "events_unnested"
friendly_name = "Ad Clicks on SERPs (Glean)"
description = "Count of ad clicks on SERPS collected by Glean"

[metrics.serps_with_ads_from_glean]
select_expression = '''
    COUNTIF(event.category = 'serp' AND event.name = 'ad_impression')
'''
data_source = "events_unnested"
friendly_name = "SERPs with Ads (Glean)"
description = "Count of SERPs with Ads collected by Glean"


[metrics.ad_clicks_on_serps_from_glean.statistics.bootstrap_mean]
[metrics.ad_clicks_on_serps_from_glean.statistics.deciles]

[metrics.serps_with_ads_from_glean.statistics.bootstrap_mean]
[metrics.serps_with_ads_from_glean.statistics.deciles]
