friendly_name = "New Tab Engagement"
description = """
    Measures engagement across surfaces on the New Tab. This includes
    metrics on user abandonment of these features.
"""

## Engagement
[metrics.newtab_searches.statistics.bootstrap_mean]
[metrics.newtab_searches.statistics.deciles]

[metrics.newtab_organic_topsite_clicks.statistics.bootstrap_mean]
[metrics.newtab_organic_topsite_clicks.statistics.deciles]

[metrics.sponsored_tile_impressions.statistics.bootstrap_mean]
[metrics.sponsored_tile_impressions.statistics.deciles]

[metrics.sponsored_tile_clicks.statistics.bootstrap_mean]
[metrics.sponsored_tile_clicks.statistics.deciles]

[metrics.organic_pocket_clicks.statistics.bootstrap_mean]
[metrics.organic_pocket_clicks.statistics.deciles]

[metrics.sponsored_pocket_clicks.statistics.bootstrap_mean]
[metrics.sponsored_pocket_clicks.statistics.deciles]

[metrics.sponsored_pocket_impressions.statistics.bootstrap_mean]
[metrics.sponsored_pocket_impressions.statistics.deciles]

## Abandonment
[metrics.newtab_homepage_enabled.statistics.boolean]
[metrics.newtab_pocket_enabled.statistics.boolean]
[metrics.newtab_sponsored_pocket_stories_enabled.statistics.boolean]
[metrics.newtab_tiles_enabled.statistics.boolean]
[metrics.sponsored_tiles_disabled.statistics.boolean]
